### PR TITLE
🐞 Fix onMessage in crossTab setup

### LINKED ISSUE #327: onMessage being trigged with old function reference cross-tab
## Bug information

The reference used to execute onMessage is the first reference of that function.
I can only reproduce this with crossTab=true, and the bug only occurs in non-leader tabs.

A minimal reproducable example can be found [here](https://codesandbox.io/s/jovial-satoshi-wkw0ug?file=/src/App.js).

_Note: you must open at least two tabs for the issue to be apparent, and it will not be present in leader tab_

### Affected Module

- `Version`: Tested 5.5.2 and 5.3 – it happens in both

### To Reproduce

See [codebox example here](https://codesandbox.io/s/jovial-satoshi-wkw0ug?file=/src/App.js).

- Open the example in two tabs.
- Click the counter so value is 2 in leader tab, and 3 in second tab.
- Wait 5 seconds for timeout, in which the leader will trigger `message()`
- Leader tab will correctly console log that counter value is 2, but second tab will log that counter value is 1.

### Expected behavior

Second tab should log updated counter value (3)

### Screenshots

https://user-images.githubusercontent.com/1502702/216826601-fb1bb297-6457-410a-be98-7f104726bbbe.mov

### System Information (please complete the following information)

 - `OS`: Mac OSX 12.0.1
 - `Device`: Macbook M1 Pro
 - `Browser Vendor`: Chrome

### Additional context

This _might_ be the culprit of the issues #289 and #293

### PR DESCRIPTION
**Pull request by tomfa**
resolves #327

### CODE REVIEW

**Comment by SupremeTechnopriest** [comment]
Thanks for the PR! I will review it later today.

**Comment by tomfa** [comment]
Bumpies

**Review by SupremeTechnopriest — APPROVED** [review]

**Comment by SupremeTechnopriest** [comment]
LGTM! Thanks for the contribution!

**Comment by SupremeTechnopriest** [comment]
Rather than bother you to make edits, I just made a few changes:

I spread the args to the emitter ref so it will be a true pass through.
```ts
onMessage: (...args) => {
  emitOnMessage.current(...args)
}
```

I used jest functions rather than collecting results in arrays:
```ts
it('Should only run the last onmessage callback (on crossTab=true)', async () => {
  const firstOnMessage = jest.fn()
  const secondOnMessage = jest.fn()

  props.crossTab = true
  const { result: leader } = idleTimer()

  props.onMessage = firstOnMessage
  const { rerender } = idleTimer()

  props.onMessage = secondOnMessage
  rerender(props)

  const data = 'foo'
  leader.current.message(data)

  await waitFor(() => secondOnMessage.mock.calls.length >= 1)

  expect(firstOnMessage).toHaveBeenCalledTimes(0)
  expect(secondOnMessage).toHaveBeenCalledWith(data)
})
```

**Pull request merged**
