### PR TITLE
Add web worker

### PR DESCRIPTION
**Pull request by bhattaraib58**
Used Web Worker to check for setTimeout and setIntervals.

As Web Worker's are free to run even on background, which solves the issue of idle timer not working due to the browser keeping the Tab on Sleep.

Issue Introduced in Chrome 87: https://searchenterprisedesktop.techtarget.com/news/252501600/Google-lowers-power-use-in-latest-Chrome-update

With the help of Web Workers and their implementation for Timeout and Interval functions, the checks will occur in the background, where Web Worker won't be paused even if JS Script is kept to sleep/paused. Allowing the Idle timer to work properly.

I have created a small Utility function as well to check if the browser supports web worker, else default back to window timeout and interval functions.

### CODE REVIEW

**Comment by SupremeTechnopriest** [comment]
Hey @bhattaraib58!

Thanks for the PR!  I've carved out some time to get v5 published over the holiday.  I will review your PR then!

**Comment by bhattaraib58** [comment]
Thanks @SupremeTechnopriest , waiting eagerly for v5 release.

**Comment by SupremeTechnopriest** [comment]
Usually Im pretty good about keeping up with issues on this project, but lately work has been very busy with a new product release.  Hopefully things get back to a normal schedule in the new year.

**Comment by bhattaraib58** [comment]
Closing this PR, this PR has issues working with web worker. I also found that test cases were failing.

**Comment by SupremeTechnopriest** [comment]
No worries.  Im in the middle of the V5 rewrite.  Starting from a clean sheet of paper.  Should have it out before the new year with this feature included.

**Pull request closed without merging**
