### PR TITLE
updated react, moved in-publish to dev dependencies

### PR DESCRIPTION
**Pull request by benmonro**

### CODE REVIEW

**Comment by SupremeTechnopriest** [comment]
Thanks @benmonro.  Ill get this merged in and published for you.

**Comment by benmonro** [comment]
Thanks for the quick merge @SupremeTechnopriest can you puslbish this to npm as well :)

**Comment by benmonro** [comment]
Thanks for the quick merge @SupremeTechnopriest ! much appreciated

**Comment by SupremeTechnopriest** [comment]
No problem! Publishing right now.

**Comment by benmonro** [comment]
didn't read the 2nd part of your comment until i pressed enter :)
  thanks!

**Comment by SupremeTechnopriest** [comment]
Having problems what that in-publish lib.  Im going to just remove it.  Standby.

**Comment by SupremeTechnopriest** [comment]
and done! @1.3.0 is now pushed to npm.

**Comment by benmonro** [comment]
oh ok.  thanks!  btw you should check out standard-version.  super awesome tool for changelogs and versioning...

**Comment by SupremeTechnopriest** [comment]
Will do that!  Thanks!

**Pull request merged**
