### PR TITLE
Clarify what is being debounced

### PR DESCRIPTION
**Pull request by kkirsche**
The use of `Debounce` in the description leads to confusion as to what is being debounced. This double usage makes it unclear whether we are debouncing the time idle or the time active. As such, this pull request clarifies by explaining that the debounce is simply the minimum idle time for the user before firing the action.

### CODE REVIEW

**Comment by kkirsche** [comment]
In my case, I asked my team at work to review it, and it was not clear to any of our team members.

**Comment by kkirsche** [comment]
Thank you — it looks like this may have been incorporated? Can’t check yet as the new docs site isn’t functional yet, but I’ll check and if not will try again.

**Comment by SupremeTechnopriest** [comment]
Yes!  Im working on getting the documentation live right now. Vercel is not playing nice.  Ill should have it up soon and everything will be much more clear!

**Comment by kkirsche** [comment]
No worries, I understand. Thanks again for your hard work and the great library

**Pull request closed without merging**
