### PR TITLE
🚿 Correct typo wether -> whether.

### PR DESCRIPTION
**Pull request by oller**
> Whether is a conjunction meaning if.
> Wether is a neutered goat or sheep.
> Weather is the state of the atmosphere.

https://www.grammarly.com/blog/wether-weather-whether/

Thanks for the great lib!

### CODE REVIEW

**Comment by SupremeTechnopriest** [comment]
Thank you for the PR!  We definitely don't mean a neutered goat.  As it stands with this commit, I cant merge it because it doesn't follow the contribution guide.  Specifically this part https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/CONTRIBUTING.md#git-commit-messages If you want to edit your commit message I can merge this in.  Otherwise I will update it on my end and push it.

The message should be `🚿 Correct typo wether -> whether.`

**Comment by oller** [comment]
Hi there.

I shall update the commit message and let you know once pushed (afk atm)

**Comment by oller** [comment]
> Thank you for the PR! We definitely don't mean a neutered goat. As it stands with this commit, I cant merge it because it doesn't follow the contribution guide. Specifically this part https://github.com/SupremeTechnopriest/react-idle-timer/blob/master/CONTRIBUTING.md#git-commit-messages If you want to edit your commit message I can merge this in. Otherwise I will update it on my end and push it.
> 
> The message should be `🚿 Correct typo wether -> whether.`

good to go @SupremeTechnopriest .  Thanks again for a very elegant lib.

**Comment by SupremeTechnopriest** [comment]
Looks good thanks!  I actually found a bunch of instances of this.  Ill go through and update them all.  Will merge this in so you get contributor creds :)

**Pull request merged**
